### ISSUE TITLE
Unexpected error : run.operator.exit.code.1 while running a concatenated data set 

### ISSUE THREAD

**Issue by MahoNagasawa** [tercen/flowjo_plugin#112]
Plugin v1.1.1, with FlowJo cluster explorer trackSOM workflow v0.0.4
FlowJo tutorial 4 sample files (LD1 A,B,C,D) singhlets/Live population was concatenated using FlowJo concatenation function (all compensated), Tercen plugin was applied to this concatenated population. Is this something to do the number of sample files and TrackSOM?

![image](https://user-images.githubusercontent.com/87133370/174142967-f4fc2726-a23d-4e55-ab9e-7ca1ac0f1faf.png)

**Comment by MahoNagasawa** [comment]
the same error code was observed on Flt-SNE. 
![image](https://user-images.githubusercontent.com/87133370/174144015-60b9bac7-43e6-4a30-82f3-17270c561c46.png)

**Comment by ginberg** [comment]
for TrackSOM we need at least 2 sample files as input, so that explains the first error.

I am not sure why the Fit-SNE doesn't work, unfortunately we can't see the root error as the logging takes too much space..maybe something to do with the memory settings. Could you share that workflow to the testTeam?

**Comment by MahoNagasawa** [comment]
I set ram 20GB then tSNE did ran so it was about the memory

https://stage.tercen.com/TestTeam/p/b6d3b2262166fb86a01864c2749323ec

**Comment by ginberg** [comment]
great! I am closing the issue in that case
