### ISSUE TITLE
Change Downsampling popup message

### ISSUE THREAD

**Issue by martin1english** [tercen/flowjo_plugin#74]
![image](https://user-images.githubusercontent.com/64135638/150952320-28c6fc72-149c-433d-b3c6-41ad861c20fe.png)

Change message to

Downsampling from [n1] data points to 30,000,000 data points across [n2] files. Reducing [n3] events to [n4] events ([n5]%).

*n5 is the percentage of the total events which will be uploaded.

Related to issue #22 

Text will change if issue #41 is implemented

**Comment by MahoNagasawa** [comment]
@ginberg I think, at least at the moment, we have decided to upload unlimited data points (so data points -1) then we don't get this message, do we? I think we need to discuss yes/no for the "downsampling" at which step, but for now this ticket should also be open because it doesn't apply for the current setting.
