### ISSUE TITLE
Auto Update doesn't work

### ISSUE THREAD

**Issue by martin1english** [tercen/flowjo_plugin#97]
I have full permissions on my folder so there is no OS security restriction.
Auto update has worked in the past for me.

https://user-images.githubusercontent.com/64135638/167583460-99dd5a79-290b-493a-bb8e-eefd12e00cbf.mp4

You see a file is downloaded but is not extracted and then is deleted again.

**Comment by ginberg** [comment]
@martin1english I also fixed this in version 1.0.8, but you can only test that with the next release. The auto-update broke when we added the documentation (pdf file) to the zip file that is produced on github so since version 1.0.5. It previously assumed there was only 1 file in the zip, I am now filtering all files in the zip by .jar extension

**Comment by ginberg** [comment]
auto update sometimes fails with this error message

`sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

it seems to be related to client configuration, so not much we can do about it in the plugin (except handle the error properly)
https://magicmonster.com/kb/prg/java/ssl/pkix_path_building_failed/
